Fix certifi TLS issue
I'm seeing a bunch of this all of a sudden:

```
OSError: Could not find a suitable TLS CA certificate bundle, invalid path:
/home/runner/work/recap/recap/venv/lib/python3.10/site-packages/certifi/cacert.pem
```

I'm pretty sure it's because `certifi` pushed a new release yesterday:

https://pypi.org/project/certifi/2023.7.22/

I'm trying to peg certifi to the previous version for all packages that use it
(transitively via `requests`).